### ISSUE TITLE
Can't register to FIST

### ISSUE THREAD

**Issue by heyfastos** [goingnowhere/volunteers-nowhere#2]
Hi,
Was trying to register using my email address to which my ticket was sent. Got am error mag claiming this is not a valid address (something like 'you need a ticket, use the email address to which the ticket was sent'). 
My ticket is low income. Could that be the problem? 
Cheers, Dan

**Comment by piemonkey** [comment]
@heyfastos Can you check now? I'm pretty sure this was just because our list of tickets hadn't synced with Quicket.
